#define ENTITY_ACCELERATION 0.08
#define ENTITY_DRAG_VERTICAL 0.02
#define ENTITY_DRAG_HORIZONTAL 0.09
#define ENTITY_TERMINAL_VELOCITY 3.92

#define ITEM_ACCELERATION 0.04
#define ITEM_DRAG_VERTICAL 0.02
#define ITEM_DRAG_HORIZONTAL 0.02
#define ITEM_TERMINAL_VELOCITY 1.96